# -*- coding: utf-8 -*-
"""Coffee_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfwOkJYwEuBh9QWh5TuYcBV3mFLs5hPU
"""

# ======================================================
# Café México — Dashboard (Altair, Q1 + GeoPandas maps)
# Archivo único: cafe_2.py (sin uploader; lee Base_Cafe.csv del repo)
#
# Requisitos recomendados (requirements.txt):
# streamlit==1.32.2
# pandas==2.2.2
# numpy==1.26.4
# altair==5.2.0
# scikit-learn==1.4.2
# scipy==1.13.0
# geopandas==0.14.4
# matplotlib==3.8.4
# shapely==2.0.4
#
# Para mapas: agregar mexico_states.geojson al repo.
# ======================================================

import os
import numpy as np
import pandas as pd
import altair as alt
import streamlit as st

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# Map deps (optional)
try:
    import geopandas as gpd
    import matplotlib.pyplot as plt
except Exception:
    gpd = None
    plt = None


# -------------------------------
# Page config
# -------------------------------
st.set_page_config(
    page_title="Café México — Dashboard",
    page_icon="☕",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -------------------------------
# Altair theme (Q1 style)
# -------------------------------
def _q1_theme():
    return {
        "config": {
            "view": {"stroke": "transparent"},
            "axis": {
                "labelFont": "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
                "titleFont": "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
                "labelFontSize": 12,
                "titleFontSize": 12,
                "gridColor": "rgba(0,0,0,0.08)",
                "tickColor": "rgba(0,0,0,0.20)",
                "domainColor": "rgba(0,0,0,0.25)",
            },
            "legend": {
                "labelFont": "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
                "titleFont": "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
                "labelFontSize": 12,
                "titleFontSize": 12,
                "orient": "right",
                "symbolSize": 120,
            },
            "title": {
                "font": "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
                "fontSize": 15,
                "anchor": "start",
            },
        }
    }


alt.themes.register("q1", _q1_theme)
alt.themes.enable("q1")
alt.data_transformers.disable_max_rows()

# -------------------------------
# CSS (spacing + cards)
# -------------------------------
st.markdown(
    """
    <style>
    .block-container {padding-top: 1.0rem; padding-bottom: 2.8rem; max-width: 1280px;}
    [data-testid="stSidebar"] {border-right: 1px solid rgba(0,0,0,0.06);}

    .hero {
      border-radius: 22px;
      padding: 20px 22px 14px 22px;
      border: 1px solid rgba(0,0,0,0.08);
      overflow: hidden;
      background: linear-gradient(120deg, rgba(20,20,20,0.92), rgba(25,75,70,0.92), rgba(60,35,25,0.92));
      background-size: 300% 300%;
      animation: gradientMove 10s ease infinite;
      box-shadow: 0 18px 45px rgba(0,0,0,0.10);
      color: white;
      margin-bottom: 0.75rem;
    }
    @keyframes gradientMove {
      0% {background-position: 0% 50%;}
      50% {background-position: 100% 50%;}
      100% {background-position: 0% 50%;}
    }
    .hero h1 {font-size: 2.0rem; margin: 0; line-height: 1.15;}
    .hero p {margin: 6px 0 0 0; color: rgba(255,255,255,0.78); font-size: 1.03rem;}
    .badge {
      display: inline-block;
      padding: 7px 10px;
      border-radius: 999px;
      background: rgba(255,255,255,0.12);
      border: 1px solid rgba(255,255,255,0.14);
      color: rgba(255,255,255,0.9);
      font-size: 0.85rem;
      margin-right: 6px;
      margin-top: 10px;
    }
    .card {
        border: 1px solid rgba(0,0,0,0.07);
        border-radius: 18px;
        padding: 14px 16px;
        background: rgba(255,255,255,0.72);
        box-shadow: 0 14px 30px rgba(0,0,0,0.05);
        margin-bottom: 1.0rem;
    }
    .muted {color: rgba(0,0,0,0.55); font-size: 0.95rem;}
    div[data-testid="stMetric"] {
        background: rgba(255,255,255,0.72);
        border: 1px solid rgba(0,0,0,0.07);
        border-radius: 16px;
        padding: 12px 16px;
        box-shadow: 0 14px 30px rgba(0,0,0,0.05);
    }
    hr {border: none; border-top: 1px solid rgba(0,0,0,0.08); margin: 1.0rem 0;}
    </style>
    """,
    unsafe_allow_html=True,
)

# ======================================================
# Column schema (adjustable)
# ======================================================

STATE_COLS = ["Veracruz", "Puebla", "Chiapas", "Oaxaca", "Guerrero"]

PRICE_MINMAX_PAIRS = [
    ("cereza_conv", "Precio mínimo por Kilo de fruto o cereza convencional", "Precio máximo por Kilo de fruto o cereza convencional"),
    ("perg_lav_conv", "Precio mínimo por Kilo de pergamino lavado convencional", "Precio máximo por Kilo de pergamino lavado convencional"),
    ("natural_conv", "Precio mínimo por Kilo de natural convencional", "Precio máximo por Kilo de natural convencional"),
    ("verde_conv", "Precio mínimo por Kilo de verde, oro, morteado convencional", "Precio máximo por Kilo de verde, oro, morteado convencional"),
    ("perg_lav_esp", "Precio mínimo por Kilo de pergamino lavado especial", "Precio máximo por Kilo de Pergamino lavado especial"),
    ("perg_honey_esp", "Precio mínimo por Kilo de pergamino honey especial", "Precio máximo por Kilo de pergamino honey especial"),
    ("perg_semilav_esp", "Precio mínimo por Kilo de pergamino semilavado especial", "Precio máximo por Kilo de pergamino semilavado especial"),
    ("natural_esp", "Precio mínimo por Kilo de natural especial", "Precio máximo por Kilo de natural especial"),
    ("verde_esp", "Precio mínimo por Kilo de café verde, oro, morteado especial", "Precio máximo por Kilo de café verde, oro o morteado especial"),
]

SPECIAL_COLS = ["verde_esp", "natural_esp", "perg_lav_esp", "perg_honey_esp", "perg_semilav_esp"]
CONV_COLS = ["verde_conv", "natural_conv", "perg_lav_conv", "cereza_conv"]
ALL_STAGE_COLS = SPECIAL_COLS + CONV_COLS

# Short labels for correlation/PCA readability
SHORT = {
    "verde_esp": "Verde_Esp",
    "natural_esp": "Natural_Esp",
    "perg_lav_esp": "PergLav_Esp",
    "perg_honey_esp": "PergHon_Esp",
    "perg_semilav_esp": "PergSemi_Esp",
    "verde_conv": "Verde_Conv",
    "natural_conv": "Natural_Conv",
    "perg_lav_conv": "PergLav_Conv",
    "cereza_conv": "Cereza_Conv",
}


# ======================================================
# Utilities
# ======================================================

def safe_numeric(s: pd.Series) -> pd.Series:
    return pd.to_numeric(s, errors="coerce")


def midpoint_or_single(a, b):
    if pd.notna(a) and pd.notna(b):
        return (a + b) / 2.0
    if pd.notna(a):
        return a
    if pd.notna(b):
        return b
    return np.nan


def derive_estado(row: pd.Series) -> str:
    for s in STATE_COLS:
        v = row.get(s, "")
        if isinstance(v, str) and v.strip():
            return v.strip()
    other = row.get("Otro (especifique)", "")
    if isinstance(other, str) and other.strip():
        return other.strip()
    return "No especificado"


def first_nonnull(row: pd.Series, cols: list[str]):
    for c in cols:
        v = row.get(c)
        if pd.notna(v):
            return v
    return np.nan


def winsorize_series(x: pd.Series, qlo=0.01, qhi=0.99):
    x = safe_numeric(x)
    if x.notna().sum() < 10:
        return x, (np.nan, np.nan)
    lo, hi = np.nanquantile(x, [qlo, qhi])
    return x.clip(lo, hi), (float(lo), float(hi))


@st.cache_data(show_spinner=False)
def build_variables(raw: pd.DataFrame) -> pd.DataFrame:
    df = raw.copy()

    # Stage prices from midpoint(min,max)
    for key, cmin, cmax in PRICE_MINMAX_PAIRS:
        if (cmin in df.columns) or (cmax in df.columns):
            a = safe_numeric(df[cmin]) if cmin in df.columns else pd.Series([np.nan] * len(df))
            b = safe_numeric(df[cmax]) if cmax in df.columns else pd.Series([np.nan] * len(df))
            df[key] = [midpoint_or_single(x, y) for x, y in zip(a, b)]
        else:
            df[key] = np.nan

    # Estado
    if any(c in df.columns for c in STATE_COLS):
        df["Estado"] = df.apply(derive_estado, axis=1)
    else:
        df["Estado"] = "No especificado"

    # Segmento
    if all(c in df.columns for c in SPECIAL_COLS):
        df["I_spec"] = df[SPECIAL_COLS].notna().any(axis=1).astype(int)
    else:
        df["I_spec"] = 0
    df["Segmento"] = np.where(df["I_spec"] == 1, "Especialidad", "Convencional")

    # p_i
    if all(c in df.columns for c in SPECIAL_COLS) and all(c in df.columns for c in CONV_COLS):
        df["p_i"] = df.apply(
            lambda r: first_nonnull(r, SPECIAL_COLS)
            if pd.notna(first_nonnull(r, SPECIAL_COLS))
            else first_nonnull(r, CONV_COLS),
            axis=1,
        )
    else:
        df["p_i"] = np.nan

    # winsor p_iW
    df["p_iW"], cuts = winsorize_series(df["p_i"], 0.01, 0.99)
    df.attrs["winsor_lo"], df.attrs["winsor_hi"] = cuts

    return df


def describe_prices(d: pd.DataFrame, col: str) -> pd.DataFrame:
    x = safe_numeric(d[col])
    if x.notna().sum() == 0:
        return pd.DataFrame()
    q = x.quantile([0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])
    out = pd.DataFrame(
        {
            "n": [int(x.notna().sum())],
            "mean": [float(x.mean())],
            "std": [float(x.std(ddof=1))],
            "min": [float(x.min())],
            "p01": [float(q.loc[0.01])],
            "p05": [float(q.loc[0.05])],
            "p10": [float(q.loc[0.10])],
            "p25": [float(q.loc[0.25])],
            "p50": [float(q.loc[0.50])],
            "p75": [float(q.loc[0.75])],
            "p90": [float(q.loc[0.90])],
            "p95": [float(q.loc[0.95])],
            "p99": [float(q.loc[0.99])],
            "max": [float(x.max())],
        }
    )
    return out


def pca_2d(X: pd.DataFrame, min_nonmissing=2):
    mask = X.notna().sum(axis=1) >= min_nonmissing
    Xs = X.loc[mask].copy()
    imp = SimpleImputer(strategy="mean")
    Ximp = pd.DataFrame(imp.fit_transform(Xs), columns=Xs.columns, index=Xs.index)
    Z = StandardScaler().fit_transform(Ximp)
    pca = PCA(n_components=2)
    scores = pca.fit_transform(Z)
    loadings = pd.DataFrame(pca.components_.T, index=Xs.columns, columns=["PC1", "PC2"])
    evr = pca.explained_variance_ratio_
    return (
        pd.DataFrame(scores, index=Xs.index, columns=["PC1", "PC2"]),
        loadings,
        evr,
    )


def premium_descriptive(d: pd.DataFrame, price_col: str):
    tmp = d.copy()
    tmp["_p"] = safe_numeric(tmp[price_col])
    tmp = tmp.dropna(subset=["_p", "Segmento"])
    if tmp["Segmento"].nunique() < 2:
        return None

    mu1 = tmp.loc[tmp["Segmento"] == "Especialidad", "_p"].mean()
    mu0 = tmp.loc[tmp["Segmento"] == "Convencional", "_p"].mean()

    tmp_pos = tmp[tmp["_p"] > 0].copy()
    if tmp_pos["Segmento"].nunique() < 2:
        dlog = np.nan
        pct = np.nan
    else:
        mlog1 = np.log(tmp_pos.loc[tmp_pos["Segmento"] == "Especialidad", "_p"]).mean()
        mlog0 = np.log(tmp_pos.loc[tmp_pos["Segmento"] == "Convencional", "_p"]).mean()
        dlog = float(mlog1 - mlog0)
        pct = float(100.0 * (np.exp(dlog) - 1.0))

    return {"delta": float(mu1 - mu0), "dlog": dlog, "pct": pct}


# ======================================================
# GeoPandas map helpers
# ======================================================

GEOJSON_DEFAULT = "mexico_states.geojson"
STATE_KEY_CANDIDATES = ["Estado", "state_name", "NAME_1", "name", "NOM_ENT"]

def _normalize_state(s: str) -> str:
    if not isinstance(s, str):
        return s
    return s.strip().lower()

@st.cache_data(show_spinner=False)
def load_states_geojson(path: str):
    if gpd is None:
        return None, "GeoPandas no está disponible (instala geopandas/matplotlib/shapely en requirements.txt)."
    if not os.path.exists(path):
        return None, f"No encontré `{path}`. Sube un geojson de estados (ej. mexico_states.geojson) al repo."
    try:
        g = gpd.read_file(path)
        return g, None
    except Exception as e:
        return None, f"No pude leer el geojson `{path}`. Error: {e}"

def make_state_map(gdf_states, stats_df, stats_col: str, title: str):
    """
    gdf_states: GeoDataFrame of states
    stats_df: DataFrame with columns ['Estado', stats_col]
    """
    if gpd is None or plt is None:
        return None, "GeoPandas/Matplotlib no disponibles."
    if gdf_states is None:
        return None, "No hay GeoDataFrame de estados."

    g = gdf_states.copy()

    # find key column for state name
    key = None
    for c in STATE_KEY_CANDIDATES:
        if c in g.columns:
            key = c
            break
    if key is None:
        return None, f"El geojson no tiene una columna de estado reconocible. Columnas: {list(g.columns)[:20]}"

    g["_k"] = g[key].apply(_normalize_state)
    s = stats_df.copy()
    s["_k"] = s["Estado"].apply(_normalize_state)

    m = g.merge(s[["_k", stats_col]], on="_k", how="left")

    # plot
    fig, ax = plt.subplots(1, 1, figsize=(8.6, 5.6), dpi=220)
    ax.set_axis_off()
    ax.set_title(title, loc="left", fontsize=11)

    # base
    m.plot(ax=ax, color="white", edgecolor="0.75", linewidth=0.6)

    # choropleth
    m.dropna(subset=[stats_col]).plot(
        ax=ax,
        column=stats_col,
        legend=True,
        edgecolor="0.75",
        linewidth=0.6,
        legend_kwds={"shrink": 0.72, "label": stats_col},
    )

    # labels (optional, small)
    try:
        cent = m.geometry.representative_point()
        for x, y, lab in zip(cent.x, cent.y, m[key].astype(str)):
            ax.text(x, y, lab[:12], fontsize=6.5, ha="center", va="center", alpha=0.75)
    except Exception:
        pass

    plt.tight_layout()
    return fig, None


# ======================================================
# Load data (no uploader)
# ======================================================

DEFAULT_DATA_PATH = "Base_Cafe.csv"
DATA_PATH = os.getenv("CAFE_DATA_PATH", DEFAULT_DATA_PATH)

if not os.path.exists(DATA_PATH):
    st.error(
        "No encontré el archivo de datos.\n\n"
        f"Busqué: `{DATA_PATH}`\n\n"
        "Solución: sube `Base_Cafe.csv` a la raíz del repo, o define `CAFE_DATA_PATH` con la ruta correcta."
    )
    st.stop()

raw = pd.read_csv(DATA_PATH)
df = build_variables(raw)

# ======================================================
# Header (interactive)
# ======================================================

header_mode = st.selectbox(
    "Modo de lectura",
    ["Vista ejecutiva", "Vista metodológica", "Vista econométrica"],
    index=0,
)

subtitle = {
    "Vista ejecutiva": "Resultados visuales y lectura rápida (prima, dispersión territorial, estructura latente).",
    "Vista metodológica": "Énfasis en construcción de variables, winsorización y lectura estadística de tablas/figuras.",
    "Vista econométrica": "Énfasis en interpretación de prima (semi-log) y estructura multivariada (correlaciones y PCA).",
}[header_mode]

st.markdown(
    f"""
    <div class="hero">
      <h1>☕ Café México — Dashboard</h1>
      <p>{subtitle}</p>
      <span class="badge">Mapas </span>
      <span class="badge">Tablas</span>
      <span class="badge">Correlaciones & PCA</span>
    </div>
    """,
    unsafe_allow_html=True,
)

# ======================================================
# Premium definition in expander (KaTeX-safe)
# ======================================================

with st.expander("Definición matemática de prima (clic para desplegar)", expanded=False):
    st.markdown("Definimos una prima como una diferencia sistemática de precios entre especialidad y convencional.")
    st.markdown("Sea el precio observado (MXN/kg):")
    st.latex(r"p_i > 0")
    st.markdown("Sea el indicador de especialidad:")
    st.latex(r"D_i \in \{0,1\}")
    st.latex(r"D_i = 1 \ \text{(especialidad)}, \qquad D_i = 0 \ \text{(convencional)}")

    st.markdown("**Prima en niveles:**")
    st.latex(r"\Delta = E[p_i \mid D_i=1] - E[p_i \mid D_i=0]")

    st.markdown("**Prima proporcional (semi-log):**")
    st.latex(r"y_i = \log(p_i)")
    st.latex(r"\Delta_{\log} = E[y_i \mid D_i=1] - E[y_i \mid D_i=0]")
    st.latex(r"\text{Prima porcentual} = 100 \cdot \left(e^{\Delta_{\log}} - 1\right)")

    st.markdown("**Control territorial (idea):**")
    st.latex(r"\log(p_i) = \alpha + \beta D_i + \gamma_s + u_i")
    st.markdown("Aquí β mide la prima dentro de estado (controlando heterogeneidad territorial mediante γ_s).")


# ======================================================
# Sidebar filters
# ======================================================

st.sidebar.markdown("## Filtros")

seg = st.sidebar.radio("Segmento", ["Todos", "Especialidad", "Convencional"], index=0)

states = sorted(df["Estado"].dropna().unique().tolist())
default_states = [s for s in ["Chiapas", "Oaxaca", "Veracruz", "Puebla", "Guerrero"] if s in states]
sel_states = st.sidebar.multiselect("Estado", states, default=default_states or states[:5])

price_mode = st.sidebar.selectbox(
    "Variable de precio",
    ["Precio base (p_i)", "Precio base winsorizado (p_iW)"] + [f"Etapa: {c}" for c in ALL_STAGE_COLS],
    index=1,
)
if price_mode.startswith("Etapa: "):
    price_col = price_mode.replace("Etapa: ", "")
else:
    price_col = "p_iW" if "winsorizado" in price_mode else "p_i"

use_log = st.sidebar.toggle("Escala logarítmica", value=False)
show_points = st.sidebar.toggle("Puntos (jitter) en boxplots", value=False)

px_series = safe_numeric(df[price_col]) if price_col in df.columns else pd.Series([np.nan] * len(df))
if px_series.notna().any():
    minp, maxp = float(np.nanmin(px_series)), float(np.nanmax(px_series))
    pr_range = st.sidebar.slider("Rango (MXN/kg)", min_value=minp, max_value=maxp, value=(minp, maxp))
else:
    pr_range = None

st.sidebar.download_button(
    "⬇️ Descargar CSV (con variables derivadas)",
    data=df.to_csv(index=False).encode("utf-8"),
    file_name="base_cafe_con_variables.csv",
    mime="text/csv",
)

# Apply filters
dff = df.copy()
dff = dff[dff["Estado"].isin(sel_states)]
if seg != "Todos":
    dff = dff[dff["Segmento"] == seg]
if pr_range is not None and price_col in dff.columns:
    s = safe_numeric(dff[price_col])
    dff = dff[(s.isna()) | ((s >= pr_range[0]) & (s <= pr_range[1]))]

# KPIs
lo, hi = df.attrs.get("winsor_lo", np.nan), df.attrs.get("winsor_hi", np.nan)
s_sel = safe_numeric(dff[price_col]) if price_col in dff.columns else pd.Series(dtype=float)

k1, k2, k3, k4 = st.columns(4)
with k1:
    st.metric("Observaciones (filtradas)", f"{len(dff):,}")
with k2:
    st.metric("Mediana", f"{np.nanmedian(s_sel):,.2f}" if s_sel.notna().any() else "—")
with k3:
    st.metric("P10–P90", f"{np.nanquantile(s_sel,0.10):,.1f}–{np.nanquantile(s_sel,0.90):,.1f}" if s_sel.notna().sum() >= 5 else "—")
with k4:
    st.metric("Winsor global (p_i)", f"{lo:,.2f} / {hi:,.2f}" if np.isfinite(lo) and np.isfinite(hi) else "—")

st.markdown("---")

# ======================================================
# Tabs
# ======================================================

tab0, tab1, tab2, tab3, tab4, tab5 = st.tabs(
    ["Resumen", "Descriptivas", "Distribuciones", "Boxplots", "Correlaciones", "PCA"]
)

# ---------------- TAB 0 ----------------
with tab0:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Vista rápida (tabla)")
    st.markdown('<div class="muted">Revisión de consistencia: faltantes, segmentación, estados y columnas de etapa.</div>', unsafe_allow_html=True)
    st.dataframe(dff.head(300), use_container_width=True, height=520)

    with st.expander("Interpretación de la tabla (cómo leerla)", expanded=True):
        st.markdown(
            "- Verifica que **Estado** esté bien codificado y que la segmentación Especialidad/Convencional sea consistente.\n"
            "- Revisa faltantes en columnas de etapa: la base es **heterogénea** y no todas las observaciones reportan todo.\n"
            "- Observa si hay valores extremos en precios: suelen aparecer en etapas de especialidad o en mercados específicos."
        )
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Construcción de precios base y winsorización (recuadro metodológico)")
    st.markdown("**(1) Mínimos y máximos por etapa:**")
    st.latex(r"\widehat{p}=\frac{p_{\min}+p_{\max}}{2}")

    st.markdown("**(2) Precio base p_i:** prioridad especialidad → convencional (primera columna no nula).")

    st.markdown("**(3) Winsorización (robustez):**")
    st.latex(r"p_i^{W}=\min\{\max\{p_i,\,q_{0.01}\},\,q_{0.99}\}")

    with st.expander("Interpretación", expanded=True):
        st.markdown(
            "- Si la mediana cambia poco al winsorizar, el **centro** del mercado es estable.\n"
            "- Si max/p99 bajan mucho, la diferencia está en la **cola** (valores extremos).\n"
            "- Esto afecta especialmente estimaciones de medias y regresiones sensibles a outliers."
        )
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Prima descriptiva (rápida) para la variable seleccionada")
    prem = premium_descriptive(dff, price_col) if (price_col in dff.columns) else None
    if prem is None:
        st.info("Se requieren ambos segmentos (Especialidad y Convencional) para estimar prima descriptiva.")
    else:
        c1, c2, c3 = st.columns(3)
        with c1:
            st.metric("Δ (media): Esp − Conv", f"{prem['delta']:,.2f} MXN/kg")
        with c2:
            st.metric("Δlog (media log)", f"{prem['dlog']:.3f}" if np.isfinite(prem["dlog"]) else "—")
        with c3:
            st.metric("Prima % aprox.", f"{prem['pct']:,.1f}%" if np.isfinite(prem["pct"]) else "—")

        with st.expander("Interpretación económica", expanded=True):
            st.markdown(
                "- **Δ** mide diferencia promedio en niveles (MXN/kg). Útil, pero sensible a colas.\n"
                "- **Δlog** y la prima % son más interpretables como diferencia proporcional.\n"
                "- Si cambias p_i por p_iW y la prima persiste, sugiere robustez a outliers.\n"
                "- Una prima “promedio” no implica causalidad: puede capturar calidad, organización, acceso a mercado, certificaciones, etc."
            )
    st.markdown("</div>", unsafe_allow_html=True)

    # --------- MAPS (GeoPandas) ----------
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Mapas por estado (GeoPandas)")

    geo_path = st.text_input("Ruta del GeoJSON de estados", value=os.getenv("CAFE_GEOJSON", GEOJSON_DEFAULT))
    g_states, g_err = load_states_geojson(geo_path)

    if g_err:
        st.warning(g_err)
        st.markdown(
            "Sugerencia: agrega un archivo `mexico_states.geojson` al repo. Debe contener geometrías de estados y una columna con el nombre del estado."
        )
    else:
        # aggregate for mapping
        base = dff.copy()
        base["_p"] = safe_numeric(base[price_col]) if price_col in base.columns else np.nan
        agg = (
            base.dropna(subset=["_p"])
            .groupby("Estado")["_p"]
            .agg(n="count", median="median", mean="mean")
            .reset_index()
        )

        stat_choice = st.selectbox("Estadístico a mapear", ["median", "mean", "n"], index=0)
        title = f"Mapa por estado: {stat_choice} de {price_col}"

        fig, ferr = make_state_map(g_states, agg.rename(columns={stat_choice: stat_choice}), stat_choice, title)

        if ferr:
            st.warning(ferr)
        else:
            st.pyplot(fig, use_container_width=True)

        with st.expander("Interpretación del mapa", expanded=True):
            st.markdown(
                "- El mapa es **descriptivo**: muestra heterogeneidad territorial en el estadístico elegido.\n"
                "- **Mediana** es preferible cuando hay colas: representa un nivel típico robusto.\n"
                "- **Media** incorpora extremos: útil si interesa el valor esperado, pero sensible.\n"
                "- **n** indica cobertura muestral: estados con n bajo deben interpretarse con cautela."
            )

    st.markdown("</div>", unsafe_allow_html=True)

# ---------------- TAB 1 ----------------
with tab1:
    left, right = st.columns(2, gap="large")

    with left:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("### Estadísticas descriptivas — p_i (original)")
        desc_pi = describe_prices(dff, "p_i")
        if desc_pi.empty:
            st.info("No hay datos en p_i con los filtros actuales.")
        else:
            st.dataframe(desc_pi.style.format("{:,.2f}"), use_container_width=True)
        with st.expander("Interpretación (más detalle)", expanded=True):
            st.markdown(
                "- **p50 (mediana)**: referencia central robusta.\n"
                "- **p75–p25 (IQR)**: dispersión del núcleo.\n"
                "- **p95–p99**: intensidad de cola; si se separa mucho de p50, hay extremos importantes.\n"
                "- **mean vs p50**: si mean ≫ p50, hay asimetría derecha (valores altos)."
            )
        st.markdown("</div>", unsafe_allow_html=True)

    with right:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("### Estadísticas descriptivas — p_iW (winsorizado)")
        desc_piW = describe_prices(dff, "p_iW")
        if desc_piW.empty:
            st.info("No hay datos en p_iW con los filtros actuales.")
        else:
            st.dataframe(desc_piW.style.format("{:,.2f}"), use_container_width=True)
        with st.expander("Interpretación (más detalle)", expanded=True):
            st.markdown(
                "- Winsor recorta extremos: se estabilizan **mean** y **std**.\n"
                "- Si p50 casi no cambia, el centro es estable.\n"
                "- Si la diferencia p_i vs p_iW es grande en mean/std, el análisis es sensible a outliers y conviene reportar robustez."
            )
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Descriptivas por Estado × Segmento (variable seleccionada)")
    if price_col not in dff.columns:
        st.warning("La variable seleccionada no existe.")
    else:
        tmp = dff.copy()
        tmp["_price"] = safe_numeric(tmp[price_col])
        g = (
            tmp.dropna(subset=["_price"])
            .groupby(["Estado", "Segmento"])["_price"]
            .agg(
                n="count",
                mean="mean",
                median="median",
                std="std",
                p10=lambda x: x.quantile(0.10),
                p90=lambda x: x.quantile(0.90),
            )
            .reset_index()
        )
        g = g.sort_values(["Estado", "Segmento"])
        st.dataframe(
            g.style.format(
                {"mean": "{:,.2f}", "median": "{:,.2f}", "std": "{:,.2f}", "p10": "{:,.2f}", "p90": "{:,.2f}"}
            ),
            use_container_width=True,
            height=560,
        )
        with st.expander("Interpretación (Estado × Segmento)", expanded=True):
            st.markdown(
                "- Compara **medianas** dentro de cada estado: evidencia de prima territorialmente controlada.\n"
                "- **p10–p90** aproxima rango “habitual”; si es ancho, el mercado es más heterogéneo.\n"
                "- Si especialidad tiene medianas más altas y dispersión menor, sugiere un segmento más “estandarizado” y valorizado.\n"
                "- Si especialidad tiene dispersión mayor, puede reflejar diversidad de microlotes/calidades/procesos."
            )
    st.markdown("</div>", unsafe_allow_html=True)

# ---------------- TAB 2 ----------------
with tab2:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Histograma interactivo (segmentado)")
    tmp = dff.dropna(subset=[price_col]).copy()
    tmp["_price"] = safe_numeric(tmp[price_col])

    if tmp.empty:
        st.info("No hay datos para graficar.")
    else:
        if use_log:
            tmp = tmp[tmp["_price"] > 0].copy()
            tmp["_x"] = np.log(tmp["_price"])
            x_enc = alt.X("_x:Q", bin=alt.Bin(maxbins=40), title="log(Precio)")
        else:
            tmp["_x"] = tmp["_price"]
            x_enc = alt.X("_x:Q", bin=alt.Bin(maxbins=40), title="Precio (MXN/kg)")

        hist = (
            alt.Chart(tmp)
            .mark_bar(opacity=0.85)
            .encode(
                x=x_enc,
                y=alt.Y("count():Q", title="Frecuencia"),
                color=alt.Color("Segmento:N", title="Segmento"),
                tooltip=[alt.Tooltip("count():Q", title="n")],
            )
            .properties(height=520)
        )

        st.altair_chart(hist.interactive(), use_container_width=True)

        with st.expander("Interpretación (histograma)", expanded=True):
            st.markdown(
                "- Si la distribución de especialidad se desplaza a la derecha, sugiere prima.\n"
                "- La cola derecha (precios muy altos) suele indicar microlotes o mercados específicos.\n"
                "- Con escala log, diferencias proporcionales son más visibles y la cola se vuelve legible."
            )
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Comparación p_i vs p_iW (misma muestra)")
    comp = dff.copy()
    comp = comp.assign(p_i=safe_numeric(comp["p_i"]), p_iW=safe_numeric(comp["p_iW"]))
    comp_long = comp.melt(id_vars=["Segmento", "Estado"], value_vars=["p_i", "p_iW"], var_name="Serie", value_name="Precio")
    comp_long = comp_long.dropna(subset=["Precio"])

    if comp_long.empty:
        st.info("No hay datos para comparar.")
    else:
        ch = (
            alt.Chart(comp_long)
            .mark_bar(opacity=0.85)
            .encode(
                x=alt.X("Precio:Q", bin=alt.Bin(maxbins=40), title="Precio (MXN/kg)"),
                y=alt.Y("count():Q", title="Frecuencia"),
                color=alt.Color("Serie:N", title="Serie"),
                tooltip=[alt.Tooltip("count():Q", title="n")],
            )
            .properties(height=520)
        )

        st.altair_chart(
            ch.facet(column=alt.Column("Segmento:N", title="")).resolve_scale(x="independent"),
            use_container_width=True,
        )

        with st.expander("Interpretación (p_i vs p_iW)", expanded=True):
            st.markdown(
                "- p_iW recorta el 1% inferior y el 1% superior.\n"
                "- Si el centro (mediana) casi no cambia, la transformación es “no invasiva”.\n"
                "- Si la separación entre segmentos permanece, la evidencia de prima es robusta.\n"
                "- Si la separación desaparece, estaba dominada por unos pocos valores extremos."
            )
    st.markdown("</div>", unsafe_allow_html=True)

# ---------------- TAB 3 ----------------
with tab3:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Boxplot por estado (segmentado)")
    if price_col not in dff.columns:
        st.warning("La variable seleccionada no existe.")
    else:
        tmp = dff.copy()
        tmp["_price"] = safe_numeric(tmp[price_col])
        tmp = tmp.dropna(subset=["_price"])

        if tmp.empty:
            st.info("No hay datos para boxplot.")
        else:
            order = tmp.groupby("Estado")["_price"].median().sort_values().index.tolist()

            if use_log:
                tmp = tmp[tmp["_price"] > 0].copy()
                tmp["_y"] = np.log(tmp["_price"])
                y_enc = alt.Y("_y:Q", title="log(Precio)")
                tooltip_price = alt.Tooltip("_price:Q", format=",.2f", title="Precio")
            else:
                tmp["_y"] = tmp["_price"]
                y_enc = alt.Y("_y:Q", title="Precio (MXN/kg)")
                tooltip_price = alt.Tooltip("_price:Q", format=",.2f", title="Precio")

            base = alt.Chart(tmp).encode(
                x=alt.X("Estado:N", sort=order, title="Estado", axis=alt.Axis(labelAngle=-35)),
                y=y_enc,
                color=alt.Color("Segmento:N", title="Segmento"),
                tooltip=[alt.Tooltip("Estado:N"), alt.Tooltip("Segmento:N"), tooltip_price],
            )

            box = base.mark_boxplot(size=26, opacity=0.85).properties(height=680)
            chart = box
            if show_points:
                pts = base.mark_circle(size=16, opacity=0.18).properties(height=680)
                chart = box + pts

            st.altair_chart(chart.interactive(), use_container_width=True)

            with st.expander("Interpretación (boxplot)", expanded=True):
                st.markdown(
                    "- Mediana por estado: nivel típico; comparaciones territoriales.\n"
                    "- IQR: dispersión del núcleo; más grande = mercado más heterogéneo.\n"
                    "- Especialidad sistemáticamente arriba (dentro de estado) sugiere prima territorialmente controlada.\n"
                    "- Diferencias entre estados reflejan estructura de mercado, acceso a compradores, organización, etc."
                )
    st.markdown("</div>", unsafe_allow_html=True)

# ---------------- TAB 4 ----------------
with tab4:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### Correlaciones entre etapas (sin encimar)")

    have_cols = [c for c in ALL_STAGE_COLS if c in dff.columns]
    if len(have_cols) < 3:
        st.warning("No hay suficientes columnas de etapa para correlaciones.")
        st.markdown("</div>", unsafe_allow_html=True)
    else:
        X = dff[have_cols].copy()
        corr_raw = X.corr(min_periods=15)
        Z = (X - X.mean()) / X.std(ddof=1)
        corr_std = Z.corr(min_periods=15)

        # rename for legibility
        corr_raw2 = corr_raw.rename(index=SHORT, columns=SHORT)
        corr_std2 = corr_std.rename(index=SHORT, columns=SHORT)
        labels = [SHORT.get(c, c) for c in have_cols]

        def heatmap(C: pd.DataFrame, title: str):
            L = C.stack(dropna=False).reset_index()
            L.columns = ["var1", "var2", "corr"]

            base = (
                alt.Chart(L)
                .mark_rect()
                .encode(
                    x=alt.X("var2:N", title="", sort=labels, axis=alt.Axis(labelAngle=-35)),
                    y=alt.Y("var1:N", title="", sort=labels),
                    color=alt.Color("corr:Q", title="Corr", scale=alt.Scale(domain=[-1, 1], scheme="redblue")),
                    tooltip=[alt.Tooltip("var1:N"), alt.Tooltip("var2:N"), alt.Tooltip("corr:Q", format=".2f")],
                )
                .properties(height=460, width=520, title=title)
            )

            text = (
                alt.Chart(L)
                .mark_text(fontSize=10)
                .encode(
                    x="var2:N",
                    y="var1:N",
                    text=alt.Text("corr:Q", format=".2f"),
                    color=alt.condition("abs(datum.corr) > 0.65", alt.value("black"), alt.value("rgba(0,0,0,0.55)")),
                )
            )
            return base + text

        cL, cR = st.columns(2, gap="large")
        with cL:
            st.altair_chart(heatmap(corr_raw2, "Correlación en niveles"), use_container_width=True)
        with cR:
            st.altair_chart(heatmap(corr_std2, "Correlación estandarizada"), use_container_width=True)

        with st.expander("Interpretación (correlaciones)", expanded=True):
            st.markdown(
                "- En niveles, algunas correlaciones pueden estar influidas por escala (magnitudes distintas por etapa).\n"
                "- En estandarizadas, se aísla co-movimiento: relaciones estructurales entre etapas.\n"
                "- Bloques de alta correlación sugieren un factor común (mercado local, shocks de oferta, intermediación).\n"
                "- Correlación baja entre procesos puede indicar segmentación real (p.ej. natural vs lavado)."
            )

        show_table = st.toggle("Mostrar tabla numérica (niveles)", value=False)
        if show_table:
            st.dataframe(corr_raw2.style.format("{:.2f}"), use_container_width=True, height=420)

        st.markdown("</div>", unsafe_allow_html=True)

# ---------------- TAB 5 ----------------
with tab5:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### PCA con precios estandarizados (biplot)")

    st.markdown("Estandarización previa:")
    st.latex(r"Z=\frac{X-\overline{X}}{s}")

    block = st.radio("Bloque PCA", ["Especialidad", "Convencional", "Todo (etapas)"], horizontal=True)

    if block == "Especialidad":
        cols = [c for c in SPECIAL_COLS if c in dff.columns]
        min_nonmissing = 2
        title = "PCA — Especialidad"
    elif block == "Convencional":
        cols = [c for c in CONV_COLS if c in dff.columns]
        min_nonmissing = 2
        title = "PCA — Convencional"
    else:
        cols = [c for c in ALL_STAGE_COLS if c in dff.columns]
        min_nonmissing = 3
        title = "PCA — Todo (etapas)"

    if len(cols) < min_nonmissing:
        st.warning("No hay suficientes columnas para correr el PCA con este bloque.")
    else:
        scores, loadings, evr = pca_2d(dff[cols], min_nonmissing=min_nonmissing)

        s = scores.copy()
        s["Segmento"] = dff.loc[s.index, "Segmento"].values
        s["Estado"] = dff.loc[s.index, "Estado"].values

        ev = pd.DataFrame({"Componente": ["PC1", "PC2"], "Varianza (%)": [evr[0] * 100, evr[1] * 100]})
        st.altair_chart(
            alt.Chart(ev)
            .mark_bar()
            .encode(
                x=alt.X("Componente:N", title=""),
                y=alt.Y("Varianza (%):Q", title="Varianza explicada (%)"),
                tooltip=[alt.Tooltip("Varianza (%):Q", format=".2f")],
            )
            .properties(height=240, title="Varianza explicada (PC1–PC2)"),
            use_container_width=True,
        )

        # Biplot
        sel = alt.selection_point(fields=["Segmento"], bind="legend")

        pts = (
            alt.Chart(s.reset_index(drop=True))
            .mark_circle(size=60, opacity=0.55)
            .encode(
                x=alt.X("PC1:Q", title="PC1"),
                y=alt.Y("PC2:Q", title="PC2"),
                color=alt.Color("Segmento:N", title="Segmento"),
                tooltip=[
                    alt.Tooltip("PC1:Q", format=".2f"),
                    alt.Tooltip("PC2:Q", format=".2f"),
                    alt.Tooltip("Estado:N"),
                    alt.Tooltip("Segmento:N"),
                ],
            )
            .add_params(sel)
            .transform_filter(sel)
            .properties(height=740, title=title)
        )

        scale = 3.0
        Ld = loadings.copy()
        Ld["x"] = 0.0
        Ld["y"] = 0.0
        Ld["x2"] = Ld["PC1"] * scale
        Ld["y2"] = Ld["PC2"] * scale
        Ld["var"] = [SHORT.get(v, v) for v in Ld.index]

        segs = alt.Chart(Ld.reset_index(drop=True)).mark_rule(opacity=0.95, strokeWidth=2.5).encode(
            x="x:Q",
            y="y:Q",
            x2="x2:Q",
            y2="y2:Q",
            tooltip=[alt.Tooltip("var:N"), alt.Tooltip("PC1:Q", format=".2f"), alt.Tooltip("PC2:Q", format=".2f")],
        )
        labels = alt.Chart(Ld.reset_index(drop=True)).mark_text(align="left", dx=6, dy=-6, fontSize=12).encode(
            x="x2:Q", y="y2:Q", text="var:N"
        )

        st.altair_chart((pts + segs + labels).interactive(), use_container_width=True)

        with st.expander("Interpretación (PCA)", expanded=True):
            st.markdown(
                "- PC1 suele capturar un **factor de valorización común** (nivel/segmento/mercado).\n"
                "- PC2 suele capturar contraste por **proceso/etapa** (lavado vs honey vs natural).\n"
                "- Flechas largas: variables dominantes. Flechas alineadas: co-movimiento.\n"
                "- Separación de puntos por segmento sugiere que el sistema de precios está estructurado por segmentación de mercado."
            )

    st.markdown("</div>", unsafe_allow_html=True)